name: ubuntu-20.04
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Sleep for 10 sec to show logs
        run: |
          sleep 10
      - uses: actions/checkout@v2
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
